### ISSUE TITLE
Android 27 bug

### ISSUE THREAD

**Issue by amorenew** [payfort/fort-android-sdk#1]
Crash happen on Api 27 
 java.lang.RuntimeException: Unable to start activity ComponentInfo{anter.mostafa.payforttest/com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

Solution:
https://stackoverflow.com/questions/47093127/facebook-android-only-fullscreen-opaque-activities-can-request-orientation

**Comment by mohannadsaleh** [comment]
Hello,

Thanks for sharing , please feel free to share and communicate issues/progress of your integration with our integration team at integration@payfort.com , in order to speed up your integration process .

All the best 
Mohannad

**Comment by amorenew** [comment]
solution 
I decompiled the library and add it as a module
https://github.com/amorenew/payfort
