### ISSUE TITLE
Scroll on keyboard show

### ISSUE THREAD

**Issue by amorenew** [payfort/fort-android-sdk#2]
View not scroll on keyboard show even I have `android:windowSoftInputMode="adjustResize"` in my activity.

![untitled](https://user-images.githubusercontent.com/2842459/33546222-832a9c70-d8f1-11e7-8370-32f952d6fd2b.png)

**Comment by mohannadsaleh** [comment]
Hello,

Thanks for sharing , please feel free to share and communicate issues/progress of your integration with our integration team at integration@payfort.com , in order to speed up your integration process .

All the best 
Mohannad

**Comment by amorenew** [comment]
solution 
I decompiled the library and add it as a module
https://github.com/amorenew/payfort

**Comment by nikulcears** [comment]
@amorenew whatever you provide link for payfort it doesn't contain any activity whatever provide by them in aar file. can you share your payfort module ?

 i want to solve some issue in it that i can't do in aar file.
