### ISSUE TITLE
AAPT2 Exception

### ISSUE THREAD

**Issue by gediajaydeep** [payfort/fort-android-sdk#6]
I am trying to implement the sdk but It shows me this error on build but shows me AAPT2Exception 
below are logs.

Android resource linking failed
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:69: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:69: error: attribute errorTextAppearance (aka tipo.orendalabs.com.payforttest:errorTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:69: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:121: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:121: error: attribute errorTextAppearance (aka tipo.orendalabs.com.payforttest:errorTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:121: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:145: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:145: error: attribute errorTextAppearance (aka tipo.orendalabs.com.payforttest:errorTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:145: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:192: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout\activity_cc_payment.xml:192: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:69: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:69: error: attribute errorTextAppearance (aka tipo.orendalabs.com.payforttest:errorTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:69: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:123: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:123: error: attribute errorTextAppearance (aka tipo.orendalabs.com.payforttest:errorTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:123: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:148: error: attribute errorEnabled (aka tipo.orendalabs.com.payforttest:errorEnabled) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:148: error: attribute errorTextAppearance (aka tipo.orendalabs.com.payforttest:errorTextAppearance) not found.
C:\Users\ALL\.gradle\caches\transforms-1\files-1.1\FORTSDKv1.5.aar\42fe6d47f94c11bc6bb5c0ae3225ed21\res\layout-ar\activity_cc_payment.xml:148: error: attribute hintTextAppearance (aka tipo.orendalabs.com.payforttest:hintTextAppearance) not found.

Can someone help me with it?

**Comment by mohannadsaleh** [comment]
Hello

Can you please check with integration@payfort.com to help you with integration issues .

Best Regards,
Mohanad

**Comment by gediajaydeep** [comment]
Hello Mohannad,
The issue is solved , you can close or delete the issue,

Thank you

**Comment by mohannadsaleh** [comment]
Thank you for your update , 
I would like to get in touch with you to dive deep on the issue and discuss the solution you have implemented , can you please send to integration@payfort.com to initiate the discussion 

Best Regards,
Mohanad

**Comment by mohitkarnajawala** [comment]
hey hi, i am getting  something like 
D:\Homepage\ShareEdu\share_edu\build\FORTSDKv1.8\.transforms\073cd126f0a2adfa7a37233fcecbe40d\jetified-FORTSDKv1.8\res\layout\activity_cc_response.xml:18: AAPT: error: attribute pressedGlowRadius (aka com.shareedu.app:pressedGlowRadius) not found.
    
D:\Homepage\ShareEdu\share_edu\build\FORTSDKv1.8\.transforms\073cd126f0a2adfa7a37233fcecbe40d\jetified-FORTSDKv1.8\res\layout\activity_cc_response.xml:31: AAPT: error: resource dimen/page_border (aka com.shareedu.app:dimen/page_border) not found.

issue while integrating the FORTSDKv1.8  in android how can i solve this, please can anybody help
