### ISSUE TITLE
Android Access Call Permission on runtime 

### ISSUE THREAD

**Issue by arunsankar8** [payfort/fort-android-sdk#9]
I have integrated the PAYFORT SDK inside the android application. When I run the SDK, Permission for accessing calls are requested by the application. Is the permission an important requirement for the working of the SDK. Can we disable the permission request and run the application. 
Thank you

**Comment by payfort1** [comment]
Hi @arunsankar8

Kindly note that this permission is required in order to detect the actual device ID and compare it with the one inlcuded in the SDK token request . The user has to approve it once ,when the app installed .

**Comment by arunsankar8** [comment]
Thanks for the information.
